apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "signet.labels" . | nindent 4 }}
  annotations: {{ toJson .Values.signet.service.annotations }}
spec:
  type: {{ .Values.signet.service.type | quote }}
  ports:
    - port: {{ .Values.signet.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "signet.selectorLabels" . | nindent 4 }}
