-- Copyright © 2026, Commonwealth Scientific and Industrial Research Organisation
-- (CSIRO) ABN 41 687 119 230. Licensed under the Apache License, Version 2.0.

-- The privileged routines the serving role executes before a tenant is known.
--
-- A correction first. The header of 0006_tenant_row_level_security.sql says the
-- policies exist for "a hand-written query, a migration, an ad-hoc join". That
-- was not true of Signet's own connection when it was written: Signet connected
-- as the owner of these tables, and Postgres exempts a table's owner from its
-- policies, so the policies constrained every connection to the database except
-- the one that mattered most. 0006 is left as it is, because an applied
-- migration is a historical record and Drizzle stores a hash of its contents;
-- the correction belongs here, in the migration that makes it false.
--
-- From this migration onward Signet connects as a non-owning serving role, and
-- every tenant-owned read and write it performs declares its tenant first. Three
-- reads cannot do that, because they are what establishes the tenant: resolving
-- /t/{slug}, resolving a personal access token's digest, and answering which
-- tenants a signed-in console user may see. They reach past the policies through
-- the routines below rather than through a privileged connection, so the process
-- holds no handle that can read an arbitrary tenant - the exemption has a fixed
-- shape that can be reviewed here and asserted against the deployed schema.
--
-- Each routine is hardened three ways, and each of the three is invisible in a
-- passing test:
--
--   - search_path is pinned, because a definer routine that resolves its table
--     references against the caller's search path runs them with the owner's
--     privileges, which is the textbook privilege escalation.
--   - execute is revoked from public, so the routine is reachable only by the
--     role the migrate command grants it to.
--   - every parameter is prefixed p_, because in a language sql function a
--     parameter whose name matches a column is resolved in favour of the column.
--     `where slug = slug` is a tautology returning every row, and the same
--     mistake in signet_tenant_ids_for_admin would return every tenant id in the
--     deployment to any signed-in console user.
--
-- The grants are not here. Every one of them names the serving role, whose name
-- is configuration rather than something Signet fixes, so they are generated by
-- servingRolePrivilegeStatements in packages/db/src/privileges.ts and applied by
-- the migrate command immediately after this file, inside the same advisory
-- lock. These routines name nobody, which is why they can be static SQL.

-- Resolves /t/{slug} before any tenant is known. Serves tenant scope
-- resolution, issuer resolution and member resolution. Returns NULL for a slug
-- that does not resolve, so a caller cannot distinguish an absent tenant from
-- one belonging to somebody else.
create or replace function signet_tenant_id_for_slug(p_slug text)
  returns uuid
  language sql stable security definer
  set search_path = pg_catalog, public
as $$ select id from tenants where slug = p_slug $$;
--> statement-breakpoint
-- Resolves a personal access token, which is presented with no tenant in the
-- request. Takes the digest, never the token, so a disclosure of this routine's
-- call history yields nothing replayable.
create or replace function signet_tenant_id_for_api_token(p_digest text)
  returns uuid
  language sql stable security definer
  set search_path = pg_catalog, public
as $$ select tenant_id from api_tokens where token_hash = p_digest $$;
--> statement-breakpoint
-- Answers "which tenants may I see", which necessarily precedes choosing one.
-- The only genuinely cross-tenant read the server performs, and it returns
-- tenant ids and nothing else.
create or replace function signet_tenant_ids_for_admin(p_admin_user_id uuid)
  returns setof uuid
  language sql stable security definer
  set search_path = pg_catalog, public
as $$
  select tenant_id from tenant_members where admin_user_id = p_admin_user_id
$$;
--> statement-breakpoint
revoke all on function signet_tenant_id_for_slug(text) from public;
--> statement-breakpoint
revoke all on function signet_tenant_id_for_api_token(text) from public;
--> statement-breakpoint
revoke all on function signet_tenant_ids_for_admin(uuid) from public;
