-- Copyright © 2026, Commonwealth Scientific and Industrial Research Organisation
-- (CSIRO) ABN 41 687 119 230. Licensed under the Apache License, Version 2.0.

-- Passkeys for console identities, and the ceremony challenges they are
-- registered and presented with.
--
-- Neither table carries a tenant isolation policy, and that is a decision rather
-- than an omission. Both hang off admin_users, which the schema already treats as
-- a person rather than a tenant's property: one human may administer several
-- tenants and carries one set of authenticators across all of them. A challenge
-- for a sign-in has no account at all until the assertion arrives, because a
-- discoverable credential is what names the account. They join admin_users and
-- admin_sessions in RLS_EXEMPT_TABLES in packages/db/src/rls.ts, each with its
-- reason, and rls.test.ts fails if a new table is neither covered nor listed.
--
-- The serving role's access to them needs nothing here. Its grants name the role,
-- whose name is configuration, so they are generated by
-- servingRolePrivilegeStatements in packages/db/src/privileges.ts and applied by
-- the migrate command immediately after this file - `grant ... on all tables in
-- schema public` covers a table created by any migration, and the standing
-- `alter default privileges` covers one created later.
--
-- public_key holds base64url COSE bytes in the clear. A WebAuthn public key is
-- not a secret: possessing it grants nothing, hashing it would make verification
-- impossible, and encrypting it would spend the master key on material the
-- browser hands out. See the column's comment in packages/db/src/schema/tenancy.ts.

CREATE TABLE "admin_passkey_challenges" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"challenge" text NOT NULL,
	"purpose" text NOT NULL,
	"admin_user_id" uuid,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin_passkeys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"admin_user_id" uuid NOT NULL,
	"credential_id" text NOT NULL,
	"public_key" text NOT NULL,
	"counter" bigint DEFAULT 0 NOT NULL,
	"transports" text[] DEFAULT '{}' NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "admin_passkey_challenges" ADD CONSTRAINT "admin_passkey_challenges_admin_user_id_admin_users_id_fk" FOREIGN KEY ("admin_user_id") REFERENCES "public"."admin_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_passkeys" ADD CONSTRAINT "admin_passkeys_admin_user_id_admin_users_id_fk" FOREIGN KEY ("admin_user_id") REFERENCES "public"."admin_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "admin_passkey_challenges_challenge_unique" ON "admin_passkey_challenges" USING btree ("challenge");--> statement-breakpoint
CREATE INDEX "admin_passkey_challenges_admin_user_id_idx" ON "admin_passkey_challenges" USING btree ("admin_user_id");--> statement-breakpoint
CREATE INDEX "admin_passkey_challenges_expires_at_idx" ON "admin_passkey_challenges" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "admin_passkeys_credential_id_unique" ON "admin_passkeys" USING btree ("credential_id");--> statement-breakpoint
CREATE INDEX "admin_passkeys_admin_user_id_idx" ON "admin_passkeys" USING btree ("admin_user_id");