-- Copyright © 2026, Commonwealth Scientific and Industrial Research Organisation
-- (CSIRO) ABN 41 687 119 230. Licensed under the Apache License, Version 2.0.

CREATE TABLE "endpoint_ticket_issuers" (
	"endpoint_id" uuid PRIMARY KEY NOT NULL,
	"issuer" text NOT NULL,
	"jwks_uri" text NOT NULL,
	"accepted_ticket_types" text[] DEFAULT '{}' NOT NULL,
	"max_token_lifetime_secs" integer DEFAULT 300 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "endpoint_trust_anchors" (
	"endpoint_id" uuid PRIMARY KEY NOT NULL,
	"issuer" text NOT NULL,
	"jwks_uri" text NOT NULL,
	"max_vouching_days" integer DEFAULT 30 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "vouched_by_issuer" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "vouched_statement_id" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "vouching_expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "endpoint_ticket_issuers" ADD CONSTRAINT "endpoint_ticket_issuers_endpoint_id_endpoints_id_fk" FOREIGN KEY ("endpoint_id") REFERENCES "public"."endpoints"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "endpoint_trust_anchors" ADD CONSTRAINT "endpoint_trust_anchors_endpoint_id_endpoints_id_fk" FOREIGN KEY ("endpoint_id") REFERENCES "public"."endpoints"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "clients_endpoint_id_vouched_statement_id_unique" ON "clients" USING btree ("endpoint_id","vouched_statement_id");--> statement-breakpoint
CREATE INDEX "clients_vouching_expires_at_idx" ON "clients" USING btree ("vouching_expires_at");--> statement-breakpoint
-- Tenant isolation for the two tables created above, in the same migration that
-- creates them, because a tenant-owned table that ships without its policy is
-- protected by the type system alone - and the type system does not bind a psql
-- session, a reporting job, or anything else that never passes through the
-- compiler.
--
-- Both reach their tenant through their own endpoint_id, exactly as endpoint_keys
-- and idp_configs do. Generated from packages/db/src/rls.ts, which is the
-- reviewable source of these predicates; rls.migration.test.ts fails when a table
-- named there has no policy created in this folder.
--
-- The serving role's access needs nothing here: its grants name the role, whose
-- name is configuration, so they are generated by servingRolePrivilegeStatements
-- in packages/db/src/privileges.ts and applied by the migrate command immediately
-- after this file.
alter table endpoint_trust_anchors enable row level security;
--> statement-breakpoint
drop policy if exists signet_tenant_isolation on endpoint_trust_anchors;
--> statement-breakpoint
create policy signet_tenant_isolation on endpoint_trust_anchors for all using (exists (
    select 1 from endpoints e
    where e.id = endpoint_trust_anchors.endpoint_id
      and e.tenant_id = nullif(current_setting('signet.tenant_id', true), '')::uuid
  ));
--> statement-breakpoint
alter table endpoint_ticket_issuers enable row level security;
--> statement-breakpoint
drop policy if exists signet_tenant_isolation on endpoint_ticket_issuers;
--> statement-breakpoint
create policy signet_tenant_isolation on endpoint_ticket_issuers for all using (exists (
    select 1 from endpoints e
    where e.id = endpoint_ticket_issuers.endpoint_id
      and e.tenant_id = nullif(current_setting('signet.tenant_id', true), '')::uuid
  ));